# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
  - darwin
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
